language: java
jdk:
- openjdk7
#- oraclejdk8
#- oraclejdk7
#- openjdk6

after_success:
- echo "<settings><servers><server><id>jzy3d-ftp</id><username>${env.CI_DEPLOY_USERNAME}</username><password>${CI_DEPLOY_PASSWORD}</password></server></servers></settings>"  > ~/settings-travis-generated.xml
- mvn deploy --settings ~/settings-travis-generated.xml -X
env:
  global:
    secure: "S5grdv+ZJp/IHEDIYhlqv6D5p94L4zDOkbxODqmzYkBnI4Kv6jsZA/Iwdw/YD6ThODwe1/A0MtpHDXfyDHIo0DCiGso4eVyMzIKMgxP0jwgqIA2+hikQdYvSDwKOWzzzvjMRQZRDNFnlp0yji2y81JYkgd9OWrcXZnWi2dWfV8s="
    secure: "IeL3/rYn3cGzzqGn/3DxKou/dCJttD9jzdzncTkFp+4snRRdOGnvRu0ApOcCXqtQ5YZiaGBW270G+NLxwCnx3XSUKDDmJwsWz5V4QvUEVGYjlyiblXOSY2ZPFGYIRM3WLgIuERM0kQ4Onf4WnZvV12n5vDL+zGAt6E9vmz9Igec="
